---
global:
  scrape_interval: 15s
  external_labels:
    monitor: prometheus
scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets:
          - localhost:9090
  - job_name: Jjtech-Flix-Webapp1
    ec2_sd_configs:
      - region: us-west-1
        access_key: AKIA4DTWY2TBQXB6GUGH
        secret_key: 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
        port: 9100
